application: ss-federation
version: 1
runtime: go
api_version: go1

handlers:
# Static folders
- url: /css
  static_dir: static/css
- url: /docs
  static_dir: static/docs
- url: /html
  static_dir: static/html
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js

# Regex for all swagger files to make as static content.
# You should create the folder static/swagger and copy
# swagger-ui into it.
#
- url: /apidocs/(.*?)/(.*\.(js|html|css))
  static_files: static/swagger/\1/\2
  upload: static/swagger/(.*?)/(.*\.(js|html|css))

# Some admin thing I think?
- url: /_ah/spi/.*
  script: _go_app

# Admin features, for database level admins.
- url: /api/admin/.*
  script: _go_app
#  login: admin

# Shard API - for shard servers, protected using tokens / sessions.
- url: /api/shard/.*
  script: _go_app

# Client API - for clients who are logged in and registered.
- url: /api/account/.*
  script: _go_app
  login: required

# Client API - for all clients.
- url: /api/client/.*
  script: _go_app

# Everything else
- url: /.*
  script: _go_app
#  login: required

